# Generated by Django 3.0.3 on 2020-07-08 21:07

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, default=None, max_length=30)),
                ('address', models.CharField(blank=True, default=None, max_length=40)),
                ('email', models.EmailField(blank=True, default=None, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_name', models.CharField(blank=True, default=None, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('value', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=20)),
                ('last_name', models.CharField(blank=True, max_length=20)),
                ('birth_date', models.DateField(default=None)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('address', models.CharField(blank=True, default=None, max_length=40)),
                ('email', models.EmailField(blank=True, default=None, max_length=40)),
                ('linkedIn', models.URLField(blank=True, default=None, null=True)),
                ('isAvailableNow', models.BooleanField(default=False, max_length=2)),
                ('salary', models.IntegerField(blank=True, default=None, null=True)),
            ],
            managers=[
                ('profiles', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(blank=True, max_length=20)),
                ('role_class', models.CharField(blank=True, default=None, max_length=20)),
                ('role_industry', models.CharField(blank=True, default=None, max_length=20)),
                ('role_description', models.CharField(blank=True, default=None, max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(blank=True, max_length=20)),
                ('rating', models.IntegerField(blank=True, default=None)),
                ('client_rating', models.IntegerField(blank=True, default=None)),
                ('years', models.FloatField(blank=True, default=None)),
                ('metric1', models.IntegerField(blank=True, default=None)),
                ('metric2', models.IntegerField(blank=True, default=None)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=30)),
                ('description', models.CharField(blank=True, default=None, max_length=264)),
                ('start_date', models.DateField(blank=True, default=None)),
                ('end_date', models.DateField(blank=True, default=None)),
                ('salary', models.IntegerField(default=None)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Hobbie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobbie_name', models.CharField(max_length=20)),
                ('hobbie_description', models.CharField(blank=True, default=None, max_length=264)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, default=None, max_length=20)),
                ('start_date', models.DateField(blank=True, default=None)),
                ('end_date', models.DateField(blank=True, default=None)),
                ('client_feedback', models.CharField(blank=True, default=None, max_length=2)),
                ('client_note', models.IntegerField(blank=True, default=None)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.Profile')),
                ('role', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='first_app.Role')),
            ],
        ),
    ]
